version: '3'
services:
  emote-bot-daemon:
     build: .
     command: >
      sh -c "npx prisma migrate dev &&
             npm start"
     volumes:
       - .:/usr/app
       - /usr/app/node_modules
     restart: always
     depends_on:
       - postgres
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always